name: movie
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  bloc_concurrency: ^0.3.0
  go_router: ^14.8.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  like_button: ^2.0.5
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/ 
    - assets/fonts/ 

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf